### ISSUE TITLE
新上位互換技術modern bert の対応

### ISSUE THREAD

**Issue by Mofa-Xingche** [tuna2134/sbv2-api#157]
**機能追加の説明**
上位互換技術modern bert の対応
https://x.com/jeremyphoward/status/1869786023963832509
なんか高速化して、性能も上がったmodernBERTとか言うの出たらしいです、stylebertvitsはbert使ってるみたいなので効率化できるのでしょうか？

**メリット**
AIがより発音うまく速くしゃべるようになる
![456306cecc5c-20241220](https://github.com/user-attachments/assets/76af815b-6a04-4639-af86-fbaac0ebbd0f)
**デメリット**
アプデが必要

**Comment by Googlefan256** [comment]
style-bert-vits2として対応するかという話だと重みが違う/日本語に対応していないため厳しいかと
このプロジェクトとしてなら変換コードを変えることなく対応できるため特段することはないです。
