### ISSUE TITLE
配布を1ファイルで済むようにする

### ISSUE THREAD

**Issue by Googlefan256** [tuna2134/sbv2-api#20]
現在の案では`tsukuyomi.sbv2`のような名前で、実態はzstdの中にmodel.onnxとstyle_vectors.jsonを配置する。圧縮レベルは標準でいいのかな?

**Comment by tuna2134** [comment]
> 現在の案では`tsukuyomi.sbv2`のような名前で、実態はzstdの中にmodel.onnxとstyle_vectors.jsonを配置する。圧縮レベルは標準でいいのかな?

あり
