### ISSUE TITLE
数字が読み上げれない

### ISSUE THREAD

**Issue by tuna2134** [tuna2134/sbv2-api#27]
Python版ではnum2wordsを採用しているので、似たようなライブラリを作ればなんとか対応できそう、、、

**Comment by tuna2134** [comment]
独自クレート作ることを決定

**Comment by sanamiy** [comment]
jpreprocess-njdは使えませんか？

https://github.com/jpreprocess/jpreprocess

**Comment by tuna2134** [comment]
使っているけど、動かない、、、

**Comment by sanamiy** [comment]
そしたらjpreprocessの方にissueかプルリクかを出してみてはどうでしょうか……？

**Comment by tuna2134** [comment]
> そしたらjpreprocessの方にissueかプルリクかを出してみてはどうでしょうか……？

修正できそうなので大丈夫です🙆
