### ISSUE TITLE
style_vectors.json について

### ISSUE THREAD

**Issue by sanamiy** [tuna2134/sbv2-api#3]
sbv2 onnx rust サーバーの公開ありがとうございます！
早速ですがただいま試させていただいてます。

READMEに記載のある通り、
`models/deberta.onnx`および、`models/model_opt.onnx`
については、
https://huggingface.co/tuna2134/tsukuyomi-onnx/tree/main
からダウンロードして配置しました。
.env.sample に記載のある style_vectors.jsonについても共有していただけませんか？

配置せずに以下を試しました。
1. `cargo run --bin sbv2_api` 
サーバーが立ったことを確認

2. curl を実行
```
curl -X POST http://localhost:3000/synthesize -H "Content-Type: application/json" -d '{"text":"合成したいテキスト"}'
```
で、`Something went wrong: IO error: No such file or directory (os error 2)` というエラーが出ています。

どうぞよろしくお願いします。

**Comment by sanamiy** [comment]
style_vectors.jsonを
https://github.com/tuna2134/Style-Bert-VITS2/blob/master/onnx/style_vectors.json
に発見しました！

このファイルをmodels フォルダ内に配置して実行してみたところ、
`Something went wrong: ONNX error: Invalid input name: style_vec` というエラーが出ました。

**Comment by tuna2134** [comment]
> style_vectors.jsonを https://github.com/tuna2134/Style-Bert-VITS2/blob/master/onnx/style_vectors.json に発見しました！
> 
> このファイルをmodels フォルダ内に配置して実行してみたところ、 `Something went wrong: ONNX error: Invalid input name: style_vec` というエラーが出ました。

昨日onnxファイル側の修正して、そのアップロードを忘れてました。
https://huggingface.co/tuna2134/tsukuyomi-onnx/tree/main/models
ここに修正版配置したのでよければ使ってみてください。

**Comment by sanamiy** [comment]
早速のアップロードありがとうございます。

onnxを差し替えて使用したところ、
 `cargo run --bin sbv2_core` では、
`Error: OrtError(Error { code: InvalidArgument, msg: "Invalid input name: x_tst" })`

`cargo run --bin sbv2_api` では、
```
curl -X POST http://localhost:3000/synthesize -H "Content-Type: application/json" -d '{"text":"合成したいテキスト"}'
```
を実行したところ、
`Something went wrong: ONNX error: Invalid input name: x_tst` とのことでした。
まだonnxに不具合が残っているかもしれません...

**Comment by tuna2134** [comment]
> 早速のアップロードありがとうございます。
> 
> onnxを差し替えて使用したところ、 `cargo run --bin sbv2_core` では、 `Error: OrtError(Error { code: InvalidArgument, msg: "Invalid input name: x_tst" })`
> 
> `cargo run --bin sbv2_api` では、
> 
> ```
> curl -X POST http://localhost:3000/synthesize -H "Content-Type: application/json" -d '{"text":"合成したいテキスト"}'
> ```
> 
> を実行したところ、 `Something went wrong: ONNX error: Invalid input name: x_tst` とのことでした。 まだonnxに不具合が残っているかもしれません...

うーん、僕の環境だと起きなかった問題ですね、、、
詳しく調べてみます。。。

**Comment by sanamiy** [comment]
ありがとうございます！
私の環境は、Ubuntu 22.04.4 LTSです。

気が付いたのですが、新たにアップロードされたmodel_opt.onnxファイルと、以前アップロードされていたdevartaファイルのファイルサイズが待ったく同じなので、新たに[model_opt.onnx](https://huggingface.co/tuna2134/tsukuyomi-onnx/blob/main/models/model_opt.onnx) としてアップロードしたファイルが、devarta ファイルかもしれません。

**Comment by tuna2134** [comment]
> ありがとうございます！ 私の環境は、Ubuntu 22.04.4 LTSです。
> 
> 気が付いたのですが、新たにアップロードされたmodel_opt.onnxファイルと、以前アップロードされていたdevartaファイルのファイルサイズが待ったく同じなので、新たに[model_opt.onnx](https://huggingface.co/tuna2134/tsukuyomi-onnx/blob/main/models/model_opt.onnx) としてアップロードしたファイルが、devarta ファイルかもしれません。

あー、huggingface-cliでuploadした際の問題かも、、、？

**Comment by tuna2134** [comment]
> ありがとうございます！ 私の環境は、Ubuntu 22.04.4 LTSです。
> 
> 気が付いたのですが、新たにアップロードされたmodel_opt.onnxファイルと、以前アップロードされていたdevartaファイルのファイルサイズが待ったく同じなので、新たに[model_opt.onnx](https://huggingface.co/tuna2134/tsukuyomi-onnx/blob/main/models/model_opt.onnx) としてアップロードしたファイルが、devarta ファイルかもしれません。

https://huggingface.co/tuna2134/tsukuyomi-onnx/tree/main/models
修正しました
