### ISSUE TITLE
WASM対応について

### ISSUE THREAD

**Issue by tuna2134** [tuna2134/sbv2-api#36]
ortが使えないので諦めていたが、wonnxが使えばいけそうなので、onnx feature指定したときはwonnxそれ以外はonnx使うようにする仕組みを用意する

**Comment by tuna2134** [comment]
実装かなり迷うなぁ

**Comment by Googlefan256** [comment]
jsから返された二重 / 三重のarrayをarray2/3に変換、またarray2,3を二重/三重のarrayに変換する部分が難しい

**Comment by Googlefan256** [comment]
callbackを利用してjs -> rust -> js -> rust -> js -> rust -> jsの流れで推論をする予定

**Comment by Googlefan256** [comment]
そろそろ閉じてもヨシ
