### ISSUE TITLE
CoreMLが利用できない

### ISSUE THREAD

**Issue by solaoi** [tuna2134/sbv2-api#55]
**バグの説明**

featuresとしてcoremlを有効化すると、下記エラーが発生してビルドできない

```
ld: Undefined symbols: ___isPlatformVersionAtLeast
```

そのため `sbv2-gui` であれば、 `src-tauri/build.rs` に下記オプションを追加する必要があります。
```
println!("cargo:rustc-link-arg=-fapple-link-rtlib");
```
https://ort.pyke.io/perf/execution-providers#coreml

**Comment by tuna2134** [comment]
僕の手元にMacがないため、動作確認はできませんが、ブランチ切ってapiの方は修正しときます。

**Comment by tuna2134** [comment]
https://github.com/tuna2134/sbv2-api/pull/56
修正のためのプルリク作成いたしました。
先ほど言った通り僕には試す環境がないため、動作確認誰かお願いします。
