### ISSUE TITLE
gRPC対応のAPIを建てるかどうか

### ISSUE THREAD

**Issue by sanamiy** [tuna2134/sbv2-api#6]
gRPCサーバーのコードを掲載するという案
コード作成済みなので作成の手間は無し

## デメリット
メンテナンスコストがかかる
元のapiのコードさえあれば、簡単にgrpcサーバーのコードは作成可能

## メリット
rust, python に限らず typescript など様々な言語で呼び出しやすい
ちょっと早い

**Comment by tuna2134** [comment]
個人的にはメンテコストがかかるのとREST APIが用意されているので別にいらないかなと思いますけど、他の方の意見はどうでしょうか？

**Comment by Googlefan256** [comment]
crates.ioにsbv2_coreを置いて、それを基に(depとして利用し、)grpc対応のサーバーを作成するのが最適かと

**Comment by sanamiy** [comment]
優先順位高いことは他に色々あるので、考えるのはあとで良さそう。
コード自体はhttps://github.com/sanamiy/sbv2-api のgrpcブランチに置いてます。

**Comment by sanamiy** [comment]
あまりRustの文化詳しくないので、お任せします。

**Comment by tuna2134** [comment]
メンテコストが増えるので採用送らせます
