### ISSUE TITLE
ジュピターノートブックが欲しいです

### ISSUE THREAD

**Issue by Mofa-Xingche** [tuna2134/sbv2-api#91]
**機能追加の説明**
ジュピターノートブックが欲しいです1

**メリット**
colabで実行できるようになります

**デメリット**

**Comment by tuna2134** [comment]
いいですね、作りましょう！

**Comment by Mofa-Xingche** [comment]
ごめんさい、私の目標メモ。
onnx化された複数話者が入れ込んである単一のStyle bert vits2モデルを音声合成できる、超高速起動できるジュピターノートブックを作ることです
pythonはcolabに標準でインストールされているが、rustはないので。rustだとcolabにインストールまでの時間がかかてしまうだからpython

**Comment by tuna2134** [comment]
複数の話者モデルの対応ですか、、、
そうですね、、、やりましょう

**Comment by Mofa-Xingche** [comment]
すみません　ありがとうございます。
複数話者のイメージ

speakername speakerID
"Lisa": 0,
"Belly": 1,
"Mai": 2,


style-name styleID
"Neutral": 0,
"Lisa-happy": 1,
"Lisa-angry": 2,
"Lisa-sad": 3,
"Belly-happy": 4,
"Belly-angry": 5,
"Belly-sad": 6,
"Mai-happy": 7,
"Mai-angry": 8,
"Mai-sad": 9,
