### ISSUE TITLE
このリポジトリのpythonのバージョンがあるととても便利です

### ISSUE THREAD

**Issue by Mofa-Xingche** [tuna2134/sbv2-api#92]
**機能追加の説明**
ごめんなさい。このリポジトリのpythonのバージョンがあるととても便利です

**メリット**
onnxのinferのみの軽いバージョンがpythonで登場させることが出来ます。ごめんなさいありがとうございますですが、Rustは使ってる人が少なく、多くの人は誰も理解と使用ができないかもしれません ごめんなさい

**デメリット**
ここにデメリットを書いてください。

**Comment by Googlefan256** [comment]
あります
https://github.com/tuna2134/sbv2-api/blob/main/sbv2_bindings/examples/basic.py

**Comment by Mofa-Xingche** [comment]
ごめんなさい。ありがとうございます、これはrustで書いたプログラムを呼び出してるpythonコードという感じですが、完全にrust無しの、onnx SBV2が実行できるpythonリポジトリはまだ存在しない感じでしょうかね
(わけあってrust一切使えないPCで実行している)

**Comment by Googlefan256** [comment]
Rustをコンパイルしなくてもビルド済みのバイナリを利用できますよ

**Comment by Mofa-Xingche** [comment]
/// テキストから音声を合成する
    ///
    /// Parameters
    /// ----------
    /// text : str
    ///     テキスト
    /// ident : str
    ///     識別子
    /// style_id : int
    ///     スタイルID
    /// sdp_ratio : float
    ///     SDP比率
    /// length_scale : float
    ///     音声の長さのスケール
    ///
    /// Returns
    /// -------
    /// voice_data : bytes
    ///     音声データ
    fn synthesize<'p>(
        &'p self,
        py: Python<'p>,
        text: String,
        ident: String,
        style_id: i32,
        sdp_ratio: f32,
        length_scale: f32,
    ) -> anyhow::Result<Bound<PyBytes>> {
        let data = self.model.easy_synthesize(
            ident.as_str(),
            &text,
            style_id,
            SynthesizeOptions {
                sdp_ratio,
                length_scale,
                ..Default::default()
            },
        )?;
        Ok(PyBytes::new_bound(py, &data))
    }

    fn unload(&mut self, ident: String) -> bool {
        self.model.unload(ident)
    }
}

このコードにおける、入力パラメータのidentは感情スタイルの名前ではなく、話者の名前ですか？
またsbv2形式は、複数の話者が入ったモデルを.sdv2に変換できますか？
さらに上記のコードは、複数の話者が入ったモデルでも音声合成できますか？

このようなモデルを想定しています

speakername speakerID
"Lisa": 0,
"Belly": 1,
"Mai": 2,


style-name styleID
"Neutral": 0,
"Lisa-happy": 1,
"Lisa-angry": 2,
"Lisa-sad": 3,
"Belly-happy": 4,
"Belly-angry": 5,
"Belly-sad": 6,
"Mai-happy": 7,
"Mai-angry": 8,
"Mai-sad": 9,

**Comment by Googlefan256** [comment]
複数の話者には現在は対応していません。identはファイル名(tsukuyomi.sbv2ならtsukuyomi)です。

**Comment by Mofa-Xingche** [comment]
すみません　ありがとうございます
このライブラリは
!pip install sbv2_bindings　だけすれば良くて、style-bert-vits2の公式リポジトリのrequirment.txtにあるような
torchとか多数のライブラリインストールしなくてもよいって事でしょうか？

あと、この.sbv2のonnx化は本来と比べてどれくらい音声合成が速くなりますか？本来は20文字0.5秒ぐらいでした

あとこの.sbv2形式以外でも音声合成できる、pythonライブラリ化した.safetensorで合成できるpipのstyle bert vits2のinferはありますか？

**Comment by tuna2134** [comment]
>すみません　ありがとうございます
このライブラリは
!pip install sbv2_bindings　だけすれば良くて、style-bert-vits2の公式リポジトリのrequirment.txtにあるような
torchとか多数のライブラリインストールしなくてもよいって事でしょうか？

そうですね

**Comment by Googlefan256** [comment]
> あとこの.sbv2形式以外でも音声合成できる、pythonライブラリ化した.safetensorで合成できるpipのstyle bert vits2のinferはありますか？
.sbv2の中身はonnxなのでsafetensors形式での推論には現在対応しておりません
> あと、この.sbv2のonnx化は本来と比べてどれくらい音声合成が速くなりますか？本来は20文字0.5秒ぐらいでした
CPUだと少なくとも * コア数分は高速化します
GPUだと環境によります。私の環境では一回"おはようございます。"を合成するのに30ミリ秒で済むくらいには高速化します。

**Comment by Mofa-Xingche** [comment]
ごめんなさい ありがとうございます
import time
from sbv2_bindings import TTSModel

def main():
    print("Loading models...")
    model = TTSModel.from_path("./models/deberta.onnx", "./models/tokenizer.json")
    print("Models loaded!")

    model.load_sbv2file_from_path("tsukuyomi", "./models/tsukuyomi.sbv2")
    print("All setup is done!")
    style_vector = model.get_style_vector("tsukuyomi", 0, 1.0)

    while True:
        # ユーザーからの入力を受け付ける
        user_input = input("合成したいテキストを入力してください（終了するには'q'と入力）：")
        if user_input.lower() == 'q':
            print("終了します。")
            break

        # 音声合成を実行
        output_file = "output.wav"

        # 時間の測定開始
        start_time = time.time()

        with open(output_file, "wb") as f:
            f.write(
                model.synthesize(user_input, "tsukuyomi", 0, 0.0, 1)
            )

        # 時間の測定終了
        end_time = time.time()

        # 合成にかかった時間を表示
        elapsed_time = end_time - start_time
        print(f"音声が '{output_file}' に保存されました。")
        print(f"音声合成にかかった時間: {elapsed_time:.2f} 秒")

if __name__ == "__main__":
    main()　





　最終的にこのコードを得ましたが、
"くわ科の一年生植物。生長が速く、茎がまっすぐに伸びて二メートルぐらいになる"
で6.41秒生成に時間かかりました(モデルのロードとか抜きで)、このコードをGPU化cudaにするにはどうしたらいいでしょうか

**Comment by Mofa-Xingche** [comment]
https://pastebin.com/2tVY6DGE

**Comment by Googlefan256** [comment]
今確認したところpython版はGPU非対応でした(対応予定はあり)
CPUでも利用可能なCPUコアをすべて消費することでかなり高速に生成されるはずなので(正常に動けばモバイル向けCPUで0.5秒で生成できるはず)原因調査します。(python bindingは主に @tuna2134 の領域なので彼に投げます。)

**Comment by Googlefan256** [comment]
なお [ここ](https://github.com/tuna2134/sbv2-api?tab=readme-ov-file#%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%82%E3%82%8B%E7%A8%8B%E5%BA%A6%E3%81%A7%E3%81%8D%E3%82%8B%E4%BA%BA%E5%90%91%E3%81%91rest-api%E8%B5%B7%E5%8B%95%E6%96%B9%E6%B3%95) にある想定された利用方法を用いることで確実に高速に生成できるので、可能ならこちらを利用するのがおすすめです。

**Comment by Googlefan256** [comment]
手元環境で合成に時間がかかる問題が再現できませんでした。できればマシン情報などがあるとありがたいです。

**Comment by Mofa-Xingche** [comment]
> 今確認したところpython版はGPU非対応でした(対応予定はあり) CPUでも利用可能なCPUコアをすべて消費することでかなり高速に生成されるはずなので(正常に動けばモバイル向けCPUで0.5秒で生成できるはず)原因調査します。(python bindingは主に @tuna2134 の領域なので彼に投げます。)

すみません、ありがとうございます。
詳しい処理時間についてはこちらのログをご覧ください
Google  Colabの無課金CPUなのでよわい環境なのでこれくらいの速度かもです

合成したいテキスト入力してください（終了するには'q'と入力）：創作メインで
音声が 'output.wav' に保存されました。
音声合成にかかった時間: 6文字  1.65 秒

合成したいテキストを入力してください（終了するには'q'と入力）：創作メインで活動しています。
音声が 'output.wav' に保存されました。
音声合成にかかった時間: 14文字  2.92 秒

合成したいテキストを入力してください（終了するには'q'と入力）：創作メインで活動しています。 髪がツンツンしているキャラが好きです。
音声が 'output.wav' に保存されました。
音声合成にかかった時間: 34文字  6.34 秒

合成したいテキストを入力してください（終了するには'q'と入力）：創作メインで活動しています。 髪がツンツンしているキャラが好きです。山田錦と大慈清水の出会いから生まれました。
音声が 'output.wav' に保存されました。
音声合成にかかった時間: 55文字  12.54 秒

**Comment by Googlefan256** [comment]
![image](https://github.com/user-attachments/assets/6394386f-8f64-4b17-9d1e-a333dd33ca59)
無課金CPUで同じスクリプトで試しましたが、この結果となっています。
マシンの調子が悪いのかもしれません。

**Comment by Mofa-Xingche** [comment]
> ![image](https://private-user-images.githubusercontent.com/55381698/377933503-6394386f-8f64-4b17-9d1e-a333dd33ca59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjcxODQsIm5iZiI6MTcyOTI2Njg4NCwicGF0aCI6Ii81NTM4MTY5OC8zNzc5MzM1MDMtNjM5NDM4NmYtOGY2NC00YjE3LTlkMWUtYTMzM2RkMzNjYTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE1NTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDVjY2Y2MmQ0NDZlZDIzMzNhNDIyODU2MmNlODgyOTk4NjMxNzE3ZGY1M2Y3OGY0MDZiNmUwODgxYThhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0JWx3Ngrm1F6wmbXq5_LSOvs5P2NIKM1Y_LLOzhTktY) 無課金CPUで同じスクリプトで試しましたが、この結果となっています。 マシンの調子が悪いのかもしれません。

Google Colabの無課金CPUなのでよわい環境なのが原因かなと思いました
。ここ2~3年の普通の20万くらいのゲーミングパソコンよりかは絶対遅いですcolab無料CPU、、だから問題は無いと思います

**Comment by Googlefan256** [comment]
そうですね、2コアなので正常そうです。
一般的なノートパソコンは4-6コアあると思うので、半分以下の時間で合成できるはずです。

**Comment by Mofa-Xingche** [comment]
すみませんありがとうございます。　

sbv2のGPU対応ってどれくらいむずかしいですか？
もしやるとしたらどんなことから調べますかドキュメントありますか
現在　sbv2_bindings　が28.4 MBですが、容量も増えますかね

**Comment by Googlefan256** [comment]
rustとpythonのパッケージの両方に関する知識が必要となります。
rust側のcudaというfeature-flagの有効化とpythonのextrasの追加が必要です。
容量については100MBほど増えると思われます。

**Comment by Mofa-Xingche** [comment]
すみません　ありがとうございます。
今回のonnx化って、GPU VRAMメモリの使用量どれくらい下がるのでしょうか.safetensor本来だと4GB(???)ぐらいだったかもです

**Comment by Mofa-Xingche** [comment]
とりあえずcolabジュピターノートブック追加しました
https://github.com/tuna2134/sbv2-api/pull/98

**Comment by Mofa-Xingche** [comment]
> > あとこの.sbv2形式以外でも音声合成できる、pythonライブラリ化した.safetensorで合成できるpipのstyle bert vits2のinferはありますか？
> 
> .sbv2の中身はonnx + style_vectorsなのでsafetensors形式での推論には現在対応しておりません
> 
> > あと、この.sbv2のonnx化は本来と比べてどれくらい音声合成が速くなりますか？本来は20文字0.5秒ぐらいでした
> > CPUだと少なくとも * コア数分は高速化します
> 
> GPUだと環境によります。私の環境では一回"おはようございます。"を合成するのに30ミリ秒で済むくらいには高速化しました。
おはよう0.03秒めちゃめちゃ速いですね。rtx4090とかを使っていますか？手法気になります

**Comment by Googlefan256** [comment]
現在4090が開いてないので4060tiの結果で、少し遅いですが。
![image](https://github.com/user-attachments/assets/d6a4aecc-2188-4d4d-b207-939d04d6d464)
Dockerで手順に従って`ghcr.io/tuna2134/sbv2-api:cuda`を動かすだけです。4060tiだと70ミリ秒ですね。4090だと30ミリまで落とせる感じです。
