### ISSUE TITLE
複数の話者モデルへの対応

### ISSUE THREAD

**Issue by tuna2134** [tuna2134/sbv2-api#93]
**機能追加の説明**
現状僕が書いたモデルは単一話者を想定しているため、複数の話者で使いたい場合、使うことができない

**メリット**
複数の話者で読み上げできる

**デメリット**
破壊的変更が行われる可能性がある

- [x] スタイルID追加
- [ ] 話者追加

**Comment by Mofa-Xingche** [comment]
すみません　ありがとうございます。
複数話者のイメージです感情スタイル付きの複数話者モデルはこんな形をしています、大体、7話者30感情スタイルぐらいまで対応できると、良いと思います(学習時のVRAM敵にそのくらいがみんな限界)

speakername speakerID
"Lisa": 0,
"Belly": 1,
"Mai": 2,

style-name styleID
"Neutral": 0,
"Lisa-happy": 1,
"Lisa-angry": 2,
"Lisa-sad": 3,
"Belly-happy": 4,
"Belly-angry": 5,
"Belly-sad": 6,
"Mai-happy": 7,
"Mai-angry": 8,
"Mai-sad": 9,

**Comment by tuna2134** [comment]
あ、感情もあるのですね、、、
色々終わったら修正します

> すみません　ありがとうございます。
> 
> 複数話者のイメージです感情スタイル付きの複数話者モデルはこんな形をしています、大体、7話者30感情スタイルぐらいまで対応できると、良いと思います(学習時のVRAM敵にそのくらいがみんな限界(１２話者50感情スタイルとかまでやったことありますが))
> 
> 
> 
> speakername speakerID
> 
> "Lisa": 0,
> 
> "Belly": 1,
> 
> "Mai": 2,
> 
> 
> 
> style-name styleID
> 
> "Neutral": 0,
> 
> "Lisa-happy": 1,
> 
> "Lisa-angry": 2,
> 
> "Lisa-sad": 3,
> 
> "Belly-happy": 4,
> 
> "Belly-angry": 5,
> 
> "Belly-sad": 6,
> 
> "Mai-happy": 7,
> 
> "Mai-angry": 8,
> 
> "Mai-sad": 9,
